// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"geek/week4/internal/biz"
	"geek/week4/internal/common"
	"geek/week4/internal/conf"
	"geek/week4/internal/data"
	"geek/week4/internal/server"
	"geek/week4/internal/service"
	"log"
)

// Injectors from wire.go:

func initApp(config *conf.ServerConfig, logger *log.Logger) *common.App {
	userRepo := data.NewUserRepo()
	userBiz := biz.NewUserBiz(userRepo)
	userService := service.NewUserService(userBiz, logger)
	httpServer0 := server.NewHttpServer0(config, userService)
	httpServer1 := server.NewHttpServer1(config, userService)
	app := newApp(logger, httpServer0, httpServer1)
	return app
}
