#服务的端口
appPort1: 7070
appPort2: 7071
#server:
#  http:
#    appPort1: 7070
#    appPort2: 7071
##数据库地址
#data:
#  database:
#    driver: mysql
#    source: root:dangerous@tcp(127.0.0.1:3306)/test?parseTime=true
#  redis:
#    addr: 127.0.0.1:6379
#    read_timeout: 0.2s
#    write_timeout: 0.2s

