// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"network/app/sbi/job/internal/biz"
	"network/app/sbi/job/internal/conf"
	"network/app/sbi/job/internal/data"
	"network/app/sbi/job/internal/server"
	"network/app/sbi/job/internal/service"
)

// Injectors from wire.go:

func initApp(confData *conf.Data, confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	consumer := data.NewKafkaConsumer(confData)
	dataData, cleanup, err := data.NewData(db, consumer, logger)
	if err != nil {
		return nil, nil, err
	}
	jobRepo := data.NewJobRepo(dataData, logger)
	jobUseCase := biz.NewJobUseCase(jobRepo, logger)
	jobService := service.NewJobService(jobUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, jobService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
